# Workflow Name

name: Vitest

on:
  pull_request:
    branches: "master"
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: yarn install # 종속성 설치

      - name: Run tests
        run: yarn test # 테스트 실행
